name: CI
on:
  - push
  - pull_request
jobs:
  nix-build:
    name: Nix build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-beta, macos-latest-xlarge]
        include:
          - os: ubuntu-beta
            system: x86_64-linux
          - os: macos-latest-xlarge
            system: aarch64-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - name: âœ… Check
        run: nix flake check --impure
      - name: ğŸš Build Shell
        run: nix build -L '.#devShells.${{ matrix.system }}.default' --impure
      - name: ğŸ“¦ Build Package
        run: nix build -L '.#packages.${{ matrix.system }}.default' --impure
